services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./prestashop_8.2.1:/app
      - ./nginx-lemp/vhost-nginx.conf:/etc/nginx/conf.d/vhost-nginx.conf
      - ./certs:/certs
    networks:
      redelamplemp:
        aliases:
          - a23alexandreme.lan

  phpserver:
    build: php-lemp
    volumes:
      - ./prestashop_8.2.1:/app
      - ./php-lemp/php-fpm.conf:/etc/php/8.2/fpm/pool.d/www.conf
      - ./php-lemp/php.ini:/etc/php/8.2/fpm/php.ini
    networks:
      redelamplemp:

  basededatos:
    image: mysql:latest
    env_file:
      - .env
    volumes:
      - ./basededatos/backup-bd.sql:/docker-entrypoint-initdb.d/backup-bd.sql
      - datos:/var/lib/mysql
    networks:
      redelamplemp:

  cliente:
    hostname: cliente
    image: brunosct/debian12-cliente-firefox
    networks:
      - redelamplemp
    environment:
    - DISPLAY=${DISPLAY}
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
volumes:
  datos:
networks:
  redelamplemp: