<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR6uTjrf\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR6uTjrf/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerR6uTjrf.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerR6uTjrf\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerR6uTjrf\appAppKernelProdContainer([
    'container.build_hash' => 'R6uTjrf',
    'container.build_id' => '7ce73df5',
    'container.build_time' => 1742140315,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR6uTjrf');
