services:
  apache:
    build: apache-php-lamp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./prestashop_8.2.1:/app
      - ./certs:/certs
      - ./apache-php-lamp/vhost-apache.conf:/etc/apache2/sites-enabled/vhost-apache.conf
      - ./apache-php-lamp/php.ini:/etc/php/8.2/apache2/php.ini
    networks:
      redelamplemp:
        aliases:
          - a23alexandreme.lan
    env_file:
      - .env.presta

  basededatos:
    image: mysql:latest
    env_file:
      - .env
    volumes:
      - ./basededatos/backup-bd.sql:/docker-entrypoint-initdb.d/backup-bd.sql
      - ./basededatos:/backup
      - datos:/var/lib/mysql
    networks:
      redelamplemp:
  cliente:
    hostname: cliente
    image: brunosct/debian12-cliente-firefox
    networks:
      - redelamplemp
    environment:
    - DISPLAY=${DISPLAY}
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
volumes:
  datos:
networks:
  redelamplemp:
